name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: copiar arquivos do repositorio
        uses: actions/checkout@v3

      - name: instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar poetry
        run: pipx install poetry

      - name: instalar dependencias
        run: poetry install

      - name: executar test
        run: poetry run pytest
            